### ISSUE TITLE
Реализовать загрузку блоков из JSON

### ISSUE THREAD

**Issue by AnriTool** [SpaTidi/GPSSCharts#26]
- [x] Создать JSON со структурно описанными блоками и ссылкой на изображением
- [x] При считывании GPSS кода, определять блоки через JSON
- [x] Определять все параметры блока, считывая их нужное положение из JSON
- [x] Изобразить полученную информацию

**Comment by AnriTool** [comment]
JSON создан

**Comment by AnriTool** [comment]
JSON дописан, Сделано считывание GPSS блоков

**Comment by SpaTidi** [comment]
Изменения проверены, ошибок не обнаружено!
Продолжайте работу

**Comment by AnriTool** [comment]
Изображение сделано. Пока в ветке AnriTool-read_from_conf

**Comment by SpaTidi** [comment]
Проверено, все отлично работает. Молодец!
